#!/bin/bash

# based on the CADDE/USP script

primerscheme="$1"

raw="$2"

library="$(basename "$raw")"

ref="$(echo "$primerscheme" | cut -d/ -f1)"

primer="$(echo "$primerscheme" | cut -d/ -f2)"

threads="12"

[ ! -d $HOME/WGS/LIBRARIES ] && mkdir $HOME/WGS/LIBRARIES

[ -d $HOME/WGS/LIBRARIES/"$library" ] && rm -rf -d $HOME/WGS/LIBRARIES/"$library"

mkdir $HOME/WGS/LIBRARIES/"$library"

mkdir $HOME/WGS/LIBRARIES/"$library"/ANALYSIS

mkdir $HOME/WGS/LIBRARIES/"$library"/CONSENSUS

mkdir $HOME/WGS/LIBRARIES/"$library"/FASTQC

cd $HOME/WGS/RAW/"$library"

for i in $(find ./ -type f -name "*.fastq.gz"); do cp "$i" ../LIBRARIES/"$library"/ANALYSIS; done

cd ../LIBRARIES/"$library"/ANALYSIS

for i in $(find ./ -type f -name "*R1*.fastq.gz" -exec basename {} \;); do mv "$i" "$(echo "$i" | rev | cut -c 25- | rev)_R1.fastq.gz"; done

for i in $(find ./ -type f -name "*R2*.fastq.gz" -exec basename {} \;); do mv "$i" "$(echo "$i" | rev | cut -c 25- | rev)_R2.fastq.gz"; done

source activate illumina

fastqc -t "$threads" -q *.fastq.gz -o ../FASTQC

cp ../../../PRIMER_SCHEMES/"$primerscheme"/"$ref".reference.fasta "$ref".reference.fasta

cp ../../../PRIMER_SCHEMES/"$primerscheme"/"$ref".score.bed "$ref".score.bed

echo "Sample@Nb of reads mapped@Average depth coverage@Bases covered >10x@Bases covered >25x@Reference covered (%)" | tr '@' '\t' > "$library".stats.txt

bwa index "$ref".reference.fasta

for i in $(find ./ -type f -name "*.fastq.gz" | while read o; do basename $o | cut -d_ -f1; done | sort | uniq)
	do
		bwa mem -t "$threads" "$ref".reference.fasta "$i"_R1.fastq.gz "$i"_R2.fastq.gz | samtools sort -@ "$threads" | samtools view -@ "$threads" -F 4 -o  "$i".mapped.sorted.bam
		samtools index -@ "$threads" "$i".mapped.sorted.bam
		ivar trim -e -i "$i".mapped.sorted.bam -b "$ref".score.bed -p "$i".trimmed
		samtools sort -@ "$threads" "$i".trimmed.bam -o "$i".trimmed.sorted.bam
		samtools index -@ "$threads" "$i".trimmed.sorted.bam
		samtools mpileup -A -B -Q 0 --reference "$ref".reference.fasta "$i".trimmed.sorted.bam | ivar consensus -p "$i" -n N -i "$i"
		samtools depth "$i".trimmed.sorted.bam > "$i".depth
		bcftools mpileup -A -B -Q 0 -f "$ref".reference.fasta "$i".trimmed.sorted.bam | bcftools call --threads "$threads" -mv --ploidy 1 -Oz -o "$i".vcf.gz
		zcat "$i".vcf.gz > "$i".vcf
		stats.sh "$i" "$library" "$ref" # CADDE/USP script
	done

cat *.fa > "$library".fasta

mafft --quiet --preservecase --thread "$threads" --reorder --6merpair --addfragments "$library".fasta 	"$ref".reference.fasta > "$library".consensus.fasta 

plot_depth.py -t "$threads" --bams *.trimmed.sorted.bam -o "$library".depth.pdf -r "$ref".reference.fasta # https://github.com/ItokawaK/Alt_nCov2019_primers

rm -rf "$ref".reference.fasta*

rm -rf "$ref".score.bed

mv "$library".consensus.fasta ../CONSENSUS

mv "$library".stats.txt ../CONSENSUS

mv "$library".depth.pdf ../CONSENSUS

echo "########################"
echo "####### Finish!! #######"
echo "########################"