#!/bin/bash

# modified CADDE/USP script
 
csv="$1"

fast5="$2"

library=`echo "$csv" | sed -e 's/\.csv//g' -e 's/.*\///g'`

threads="12"

gpu="64" # NVIDIAGeForceRTX2060=32; NVIDIAGeForceRTX2080=64

callers="46" # NVIDIAGeForceRTX2060=60; NVIDIAGeForceRTX2080=46

[ ! -d $HOME/WGS/LIBRARIES ] && mkdir $HOME/WGS/LIBRARIES

[ -d $HOME/WGS/LIBRARIES/"$library" ] && rm -rf -d $HOME/WGS/LIBRARIES/"$library"

mkdir $HOME/WGS/LIBRARIES/"$library"

mkdir $HOME/WGS/LIBRARIES/"$library"/ANALYSIS

mkdir $HOME/WGS/LIBRARIES/"$library"/CONSENSUS

cd $HOME/WGS/LIBRARIES/"$library"

guppy_basecaller -x auto --gpu_runners_per_device "$gpu" --num_callers "$callers" -r -i "$fast5" -s HAC_BASECALL -c dna_r9.4.1_450bps_hac.cfg --qscore_filtering --verbose_logs

guppy_barcoder -t "$threads" -r -i HAC_BASECALL -s DEMUX --arrangements_files "barcode_arrs_nb12.cfg barcode_arrs_nb24.cfg" --require_barcodes_both_ends --trim_barcodes

cd ANALYSIS

source activate minion-qc

pycoQC -q -f ../HAC_BASECALL/sequencing_summary.txt -b ../DEMUX/barcoding_summary.txt -o "$library"_QC.html --report_title "$library"

echo "Sample@Nb of reads mapped@Average depth coverage@Bases covered >10x@Bases covered >25x@Reference covered (%)" | tr '@' '\t' > "$library".stats.txt

source activate minion

for i in `cat "$csv"`
	do
		sample=`echo "$i" | awk -F"," '{print $1}' | sed '/^$/d'`
		barcode=`echo "$i"| awk -F"," '{print $2}' | sed '/^$/d'` ; barcodeNB=`echo "$barcode" | sed -e 's/BC//g'`
		pathref=`echo "$i" | awk -F"," '{print $3}' | sed '/^$/d'`
		ref=`echo "$pathref" | sed -e 's/\/.*//g'`
		min=`awk -F"\t" '{if (($4 !~ /LEFT_alt[0-9]*$/) && ($4 !~ /RIGHT_alt[0-9]*$/)) {print $0}}' ../../../PRIMER_SCHEMES/"$pathref"/"$ref".scheme.bed | awk -F"\t" '{print $2,$3}' | tr '\n' ' ' | awk '{for (i=1;i<=(NF/2);i=i+2) {print $(i*2+1)-$(i*2)}}' | sort -n | awk 'NR==1{print}' | awk '{print $1}'`
		max=`awk -F"\t" '{if (($4 !~ /LEFT_alt[0-9]*$/) && ($4 !~ /RIGHT_alt[0-9]*$/)) {print $0}}' ../../../PRIMER_SCHEMES/"$pathref"/"$ref".scheme.bed | awk -F"\t" '{print $2,$3}' | tr '\n' ' ' | awk '{for (i=1;i<=(NF/2);i=i+2) {print $(i*2+1)-$(i*2)}}' | sort -nr | awk 'NR==1{print}' | awk '{print $1+200}'`
		artic guppyplex --min-length "$min" --max-length "$max" --directory ../DEMUX/barcode"$barcodeNB" --prefix "$library" ; mv "$library"_barcode"$barcodeNB".fastq BC"$barcodeNB"_"$library".fastq
		if [ `echo "$barcode" | awk '{if ($0 ~ /-/) {print "yes"} else {print "no"}}'` == "yes" ] ; then for i in `echo "$barcode" | tr '-' '\n'` ; do cat "$i"_"$library".fastq ; done > "$barcode"_"$library".fastq ; fi
		artic minion --threads 12 --medaka --medaka-model r941_min_high_g360 --normalise 200 --read-file "$barcode"_"$library".fastq --scheme-directory ../../../PRIMER_SCHEMES "$pathref" "$sample"
		stats.sh "$sample" "$library" "$pathref"
	done

cat *.consensus.fasta > "$library".consensus.fasta

mv "$library".consensus.fasta ../CONSENSUS

mv "$library".stats.txt ../CONSENSUS

echo "########################"
echo "####### Finish!! #######"
echo "########################"