#!/bin/bash

guppy_version=4.4.1

[ ! -d "$HOME/softwares" ] && mkdir -p $HOME/softwares

[ -d "$HOME/softwares/ont-guppy" ] && rm -rf $HOME/softwares/ont-guppy

cd $HOME/softwares

curl https://mirror.oxfordnanoportal.com/software/analysis/ont-guppy_"$guppy_version"_linux64.tar.gz -o $HOME/softwares/ont-guppy.tar.gz

tar -vzxf ont-guppy.tar.gz

rm -rf ont-guppy.tar.gz

export PATH=$HOME/softwares/ont-guppy/bin:/usr/local/share/rsi/idl/bin:$PATH

echo 'export PATH=$HOME/softwares/ont-guppy/bin:/usr/local/share/rsi/idl/bin:$PATH' >> $HOME/.bashrc

echo 'export PATH=$HOME/softwares/ont-guppy/bin:/usr/local/share/rsi/idl/bin:$PATH' >> $HOME/.zshrc
