#!/bin/bash

source activate vgap_assembly

bcftools consensus -f "$1".preconsensus.fasta "$1".pass.vcf.gz -m "$1".coverage_mask.txt -o "$1".consensus.fasta 2> "$1".bcftools_unmatch.txt

UNMATCH=$(cat "$1".bcftools_unmatch.txt | grep match | awk -F: '{print $2}')

echo ""
echo "1> Remove the line with "$UNMATCH" nucleotide variant from "$1".merged.vcf"
echo "2> Create "$1".vcf_disagreement.txt and place the line removed from "$1".merged.vcf"
