#!/bin/bash

# author: Laise de Moraes <laisepaixao@live.com>
# institution: Universidade Federal da Bahia, Brazil
# URL: https://github.com/lpmor22
# date: 24 NOV 2020

THREADS="12"

INPUT=$1

OUTPUT=$(basename "${INPUT}" | cut -d. -f1)

source activate phy

nohup clustalo --threads=${THREADS} --seqtype={Protein} --verbose -i ${INPUT} -o ${OUTPUT}_aln.fasta

mv nohup.out ${OUTPUT}_aln_log.txt
