#!/bin/bash

python -c "from datetime import datetime as dt

import time

date_entry = input('Enter a date in YYYY-MM-DD format: ')

def toYearFraction(date):

    def sinceEpoch(date):

        return time.mktime(date.timetuple())

    s = sinceEpoch

    year = date.year

    startOfThisYear = dt(year=year, month=1, day=1)

    startOfNextYear = dt(year=year+1, month=1, day=1)

    yearElapsed = s(date) - s(startOfThisYear)

    yearDuration = s(startOfNextYear) - s(startOfThisYear)

    fraction = yearElapsed/yearDuration

    return date.year + fraction

print (toYearFraction(dt.fromisoformat(date_entry)))"
