#!/bin/bash

# author: Laise de Moraes <laisepaixao@live.com>
# institution: Universidade Federal da Bahia, Brazil
# URL: https://github.com/lpmor22
# date: 24 APR 2021

THREADS="12"

INPUT=$1

OUTPUT=$(basename "${INPUT}" | cut -d. -f1)

source activate phy

nohup seqkit fx2tab -j ${THREADS} ${INPUT} > ${OUTPUT}.txt

rm -rf nohup.out
