#!/bin/bash

# author: Laise de Moraes <laisepaixao@live.com>
# institution: Oswaldo Cruz Foundation, Gonçalo Moniz Institute, Bahia, Brazil
# URL: https://lpmor22.github.io
# date: 29 MAY 2021

THREADS="$(lscpu | grep 'CPU(s):' | awk '{print $2}')"

INPUT=$1

OUTPUT=$(basename "${INPUT}" | cut -d. -f1)

source activate phy

nohup seqkit fx2tab -j ${THREADS} ${INPUT} > ${OUTPUT}.txt

rm -rf nohup.out
