#!/bin/bash

bg() {

    THREADS=$(lscpu | grep 'CPU(s):' | awk '{print $2}' | sed -n '1p')

    LIST=$1

    INPUT=$2

    OUTPUT=$(basename ${INPUT%.*})

    source activate phy

    seqkit grep -j $THREADS -nv -f $LIST $INPUT > $OUTPUT.filt.fasta

}

bg $1 $2 >/dev/null 2>&1 &
