#!/bin/sh

bg() {
    LIST=$1
    INPUT=$2
    OUTPUT=$(basename ${INPUT%.*})
    source activate phy
    seqkit grep -j ${nproc} -nv -f "$LIST" "$INPUT" > "$OUTPUT".filt.fasta
    seqkit grep -j ${nproc} -n -f "$LIST" "$INPUT" > "$OUTPUT".subsampling.fasta
}

bg $1 $2 >/dev/null 2>&1 &
