#!/bin/bash

bg() {

    THREADS=$(lscpu | grep 'CPU(s):' | awk '{print $2}' | sed -n '1p')

    INPUT=$1

    OUTPUT=$(basename ${INPUT%.*})

    source activate phy

    seqkit grep -vsrip '[WSKMYRVHDB]' -j "$THREADS" "$INPUT" > "$OUTPUT".rmAmbiguos.fasta

    seqkit grep -srip '[WSKMYRVHDB]' -j "$THREADS" "$INPUT" > "$OUTPUT".ambiguos.fasta

}

bg $1 >/dev/null 2>&1 &
