#!/bin/bash

bg() {

    THREADS=$(lscpu | grep 'CPU(s):' | awk '{print $2}' | sed -n '1p')

    INPUT=$1

    OUTPUT=$(basename ${INPUT%.*})

    source activate phy

    seqkit rmdup -j "$THREADS" -s "$INPUT" -D "$OUTPUT".dupList.txt -d "$OUTPUT".dup.fasta > "$OUTPUT".rmDup.fasta

}

bg $1 >/dev/null 2>&1 &
