#!/bin/sh

bg() {
    THREADS=$(nproc)
    INPUT=$1
    OUTPUT=$(basename ${INPUT%.*})
    source activate phy
    seqkit grep -vsrip '[WSKMYRVHDB]' -j "$THREADS" "$INPUT" > "$OUTPUT".rmAmbiguos.fasta
    seqkit grep -srip '[WSKMYRVHDB]' -j "$THREADS" "$INPUT" > "$OUTPUT".ambiguos.fasta
}

bg $1 >/dev/null 2>&1 &
