#!/bin/bash

bg() {

    THREADS=$(lscpu | grep 'CPU(s):' | awk '{print $2}' | sed -n '1p')

    INPUT=$1

    OUTPUT=$(basename ${INPUT%.*})

    source activate phy

    gbmunge -s -i $INPUT -f $OUTPUT.fasta -o $OUTPUT.txt

}

bg $1 >/dev/null 2>&1 &
