#!/bin/bash

# author: Laise de Moraes <laisepaixao@live.com>
# institution: Oswaldo Cruz Foundation, Gonçalo Moniz Institute, Bahia, Brazil
# URL: https://lpmor22.github.io
# date: 24 APR 2021

INPUT=$(basename "$1")

OUTPUT=$(basename "${FILE}" | cut -d. -f1)

source activate phy

nohup gbmunge -s -i ${INPUT} -f ${OUTPUT}.fasta -o ${OUTPUT}.txt

rm -rf nohup.out
