#!/bin/bash

# author: Laise de Moraes <laisepaixao@live.com>
# institution: Universidade Federal da Bahia, Brazil
# URL: https://github.com/lpmor22
# date: 24 NOV 2020

THREADS="12"

INPUT=$(basename "$1")

OUTPUT=$(basename "${INPUT}" | cut -d. -f1)

source activate phy

nohup iqtree -T ${THREADS} -nt AUTO -bb 1000 -bnni -m TEST -s ${INPUT}

mv nohup.out ${OUTPUT}_log.txt
