#!/bin/bash

# author: Laise de Moraes <laisepaixao@live.com>
# institution: Oswaldo Cruz Foundation, Gonçalo Moniz Institute, Bahia, Brazil
# URL: https://lpmor22.github.io
# date: 30 MAY 2021

THREADS="$(lscpu | grep 'CPU(s):' | awk '{print $2}' | sed -n '1p')"

INPUT=$1

OUTPUT=$(basename "${INPUT}" | cut -d. -f1)

source activate phy

nohup mafft --thread ${THREADS} --auto --inputorder --out ${INPUT} > ${OUTPUT}_aln.fasta 2> nohup.out

mv nohup.out ${OUTPUT}_aln_log.txt
