#!/bin/bash

# author: Laise de Moraes <laisepaixao@live.com>
# institution: Universidade Federal da Bahia, Brazil
# URL: https://github.com/lpmor22
# date: 21 MAR 2021

THREADS="12"

INPUT=$1

REFERENCE=$2

OUTPUT=$(basename "${INPUT}" | cut -d. -f1)

source activate phy

nohup mafft --thread ${THREADS} --inputorder --6merpair --addfragments ${INPUT} ${REFERENCE} > ${OUTPUT}_aln.fasta 2> nohup.out

mv nohup.out ${OUTPUT}_aln_log.txt
