#!/bin/bash

bg() {

    THREADS=$(lscpu | grep 'CPU(s):' | awk '{print $2}' | sed -n '1p')

    INPUT=$1

    REFERENCE=$2

    OUTPUT=$(basename ${INPUT%.*})

    source activate phy

    mafft --thread "$THREADS" --auto --keeplength --inputorder --6merpair --leavegappyregion --addfragments "$INPUT" "$REFERENCE" > aln.tmp

    sed '/>/!y/atcgn-/ATCGNN/' aln.tmp > "$OUTPUT".aln.fasta

    rm aln.tmp

}

bg $1 $2 >/dev/null 2>&1 &
