#!/bin/bash

THREADS="12"

INPUT=$1

REFERENCE=$2

OUTPUT=$(basename "${INPUT}" | cut -d. -f1)

source activate phy

nohup mafft --thread ${THREADS} --inputorder --6merpair --addfragments ${INPUT} ${REFERENCE} > ${OUTPUT}_aln.fasta 2> nohup.out

mv nohup.out ${OUTPUT}_aln_log.txt
