#!/bin/sh

bg() {
    THREADS=$(nproc)
    INPUT=$1
    REFERENCE=$2
    OUTPUT=$(basename ${INPUT%.*})
    source activate phy
    mafft --thread "$THREADS" --auto --inputorder --6merpair --leavegappyregion --addfragments "$INPUT" "$REFERENCE" > aln.tmp
    sed '/>/!y/atcgn/ATCGN/' aln.tmp > "$OUTPUT".aln.fasta
    rm aln.tmp
}

bg $1 $2 >/dev/null 2>&1 &
