#!/bin/bash
# author: Laise de Moraes <laisepaixao@live.com>
# institution: Oswaldo Cruz Foundation, Gonçalo Moniz Institute, Bahia, Brazil
# URL: https://lpmor22.github.io
# date: 10 JUN 2021

background() {

    start=$(date +%s.%N)

    THREADS=$(lscpu | grep 'CPU(s):' | awk '{print $2}' | sed -n '1p')

    INPUT=$1

    REFERENCE=$2

    OUTPUT=$(basename ${INPUT%.*})

    source activate phy

    mafft --thread $THREADS --auto --keeplength --inputorder --6merpair --leavegappyregion --addfragments $INPUT $REFERENCE > $OUTPUT.aln.fasta

    end=$(date +%s.%N)

    runtime=$(python -c "print(${end} - ${start})")

    echo "" && echo "Done. The runtime was $runtime seconds."

}

LOG=$(basename ${1%.*})

background $1 $2 &>$LOG.log.txt &
