#!/bin/bash

THREADS="12"

INPUT=$1

OUTPUT=$(basename "${INPUT}" | cut -d. -f1)

source activate phy

nohup mafft --thread ${THREADS} --auto --inputorder --out ${INPUT} > ${OUTPUT}_aln.fasta 2> nohup.out

mv nohup.out ${OUTPUT}_aln_log.txt
