#!/bin/bash

# author: Laise de Moraes <laisepaixao@live.com>
# institution: Universidade Federal da Bahia, Brazil
# URL: https://github.com/lpmor22
# date: 18 JAN 2021

cd $HOME
git clone git://github.com/cov-lineages/pangolin.git
cd pangolin
conda env create -f environment.yml
source activate pangolin
python setup.py install
pangolin -v
pangolin -pv
pangolin -lv
