#!/bin/bash

# author: Laise de Moraes <laisepaixao@live.com>
# institution: Universidade Federal da Bahia, Brazil
# URL: https://github.com/lpmor22
# date: 18 JAN 2021

cd $HOME/pangolin
source activate pangolin
git pull
python setup.py install
conda env update -f environment.yml
pip install git+https://github.com/cov-lineages/pangoLEARN.git --upgrade
pip install git+https://github.com/cov-lineages/lineages.git --upgrade
source activate pangolin
pangolin -v
pangolin -pv
pangolin -lv
