#!/bin/bash

# author: Laise de Moraes <laisepaixao@live.com>
# institution: Universidade Federal da Bahia, Brazil
# URL: https://github.com/lpmor22
# date: 16 MAR 2021

THREADS="12"

INPUT=$1

OUTPUT=$(basename "${INPUT}" | cut -d. -f1)

source activate phy

nohup seqkit sort -j ${THREADS} ${INPUT} > ${OUTPUT}.sorted.fasta

rm -rf nohup.out
