#!/bin/bash

FASTA=$(basename "$1" | cut -d. -f1)

source activate phy

nohup mafft --thread 12 --auto --inputorder --out ${FASTA}_aln.fasta ${FASTA}.fasta

nohup clustalo -i ${FASTA}.fasta -o ${FASTA}_aln.fasta --seqtype={Protein} --verbose

mv nohup.out ${FASTA}_aln_log.txt