#!/bin/bash

# author: Laise de Moraes <laisepaixao@live.com>
# institution: Oswaldo Cruz Foundation, Gonçalo Moniz Institute, Bahia, Brazil
# URL: https://lpmor22.github.io
# date: 24 APR 2021

if [[ -z "$(which mamba)" ]]; then
	cd
	wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
	bash Miniconda3-latest-Linux-x86_64.sh -bfp miniconda3 && rm Miniconda3-latest-Linux-x86_64.sh
	echo 'export PATH=$HOME/miniconda3/bin:/usr/local/share/rsi/idl/bin:$PATH' >> $HOME/.bashrc
	export PATH=$HOME/miniconda3/bin:/usr/local/share/rsi/idl/bin:$PATH
	conda install -y -c conda-forge mamba
	mamba update -y -n base conda
	if [[ -z "$(which mamba)" ]]
	then
    mamba update -y -n base conda
	mamba --version
  else
    mamba update -y -n base conda
	mamba --version
  fi
else
  mamba update -y -n base conda
  mamba --version
fi
