#!/bin/bash

# author: Laise de Moraes <laisepaixao@live.com>
# institution: Oswaldo Cruz Foundation, Gonçalo Moniz Institute, Bahia, Brazil
# URL: https://lpmor22.github.io
# date: 20 JUN 2021

if [[ -z "$(which mamba)" ]]; then
    conda install -y -c conda-forge mamba
    mamba update -y -n base conda
    mamba create -y -n phy -c conda-forge -c bioconda -c defaults gbmunge iqtree mafft seqkit
else
    mamba update -y -n base conda
    mamba create -y -n phy -c conda-forge -c bioconda -c defaults gbmunge iqtree mafft seqkit
fi
