#!/bin/bash

sudo apt-get update -y

sudo apt-get full-upgrade -y

sudo apt-get autoremove

sudo apt-get clean

sudo apt-get purge -y $(dpkg -l | awk '/^rc/ {print $2}')

sudo apt-get check

conda clean --all -y
