#!/bin/bash

[ ! -d "$HOME/softwares" ] && mkdir -p $HOME/softwares

[ -d "$HOME/softwares/miniconda3" ] && rm -rf $HOME/softwares/miniconda3

cd $HOME/softwares

wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh

bash Miniconda3-latest-Linux-x86_64.sh -bfp $HOME/softwares/miniconda3

rm Miniconda3-latest-Linux-x86_64.sh

export PATH="$HOME/softwares/miniconda3/bin:/usr/local/share/rsi/idl/bin:$PATH"

echo 'export PATH=$HOME/softwares/miniconda3/bin:/usr/local/share/rsi/idl/bin:$PATH' >> $HOME/.bashrc

echo 'export PATH=$HOME/softwares/miniconda3/bin:/usr/local/share/rsi/idl/bin:$PATH' >> $HOME/.zshrc

conda install -c conda-forge mamba

mamba update -y -n base conda
