#!/bin/bash

bg() {
    INPUT=$1
    OUTPUT=$(basename ${INPUT%.*})
    micromamba activate phy
    seqkit rmdup -j $(nproc) -s $INPUT -D $OUTPUT.dupList.txt -d $OUTPUT.dup.fasta > $OUTPUT.rmDup.fasta
}

bg $1 >/dev/null 2>&1 &