#!/bin/bash

sudo apt update -y
sudo apt upgrade -y
sudo apt autoremove -y
sudo apt clean -y
sudo apt purge -y $(dpkg -l | awk '/^rc/ {print $2}')
sudo apt install -fy
export PATH=$(echo -n $PATH | awk -v RS=: -v ORS=: '!a[$0]++' | sed 's/:$//')
micromamba clean --all -y