#!/bin/bash

if [[ -z "$(which guppy_basecaller)" ]]; then
    version=5.0.11
    cd
    curl https://mirror.oxfordnanoportal.com/software/analysis/ont-guppy_"$version"_linux64.tar.gz -o ont-guppy.tar.gz
    tar -vzxf ont-guppy.tar.gz
    rm -rf ont-guppy.tar.gz
    MYSHELL=$(echo $SHELL | awk -F/ '{print $NF}')
    echo 'export PATH=$HOME/ont-guppy/bin:/usr/local/share/rsi/idl/bin:$PATH' >> $HOME/.${MYSHELL}rc
    export PATH=$HOME/ont-guppy/bin:/usr/local/share/rsi/idl/bin:$PATH
else
    guppy_basecaller --version
fi
