#!/bin/bash

while getopts ":r:s:dt:" opt; do
    case $opt in
        r ) RAWPATH="$OPTARG";;
        s ) PRIMERSCHEME="$OPTARG";;
        d ) PLOTDEPTH=yes;;
        t ) THREADS="$OPTARG";;
    esac
done
shift $((OPTIND -1))

if [[ -z "$RAWPATH" ]] || [[ -z "$PRIMERSCHEME" ]] || [[ -z "$THREADS" ]]; then
    echo "Assembly pipeline for WGS using Illumina

Usage: $(basename $0) [-r RAWPATH] [-s PRIMERSCHEME] [-t THREADS]

-r  The FULL PATH to the directory containing the raw sequencing data downloaded from Illumina's BaseSpace Sequence Hub (fastq.gz files).
-s  The prime scheme information (example: nCoV-2019/FIOCRUZ_2kb_v1 or nCoV-2019/ARTIC_V3).
-d  Generates depth plots in PDF file from BAM files to briefly check coverages.
-t  Num tasks to process concurrently."
    exit 1
fi

assembly_illumina.sh $PRIMERSCHEME $RAWPATH $THREADS >> $HOME/VirWGS/LIBRARIES/$(basename $RAWPATH)_log.txt

if [[ -n "$PLOTDEPTH" ]]; then
    source activate plot
    for i in $(find $HOME/VirWGS/LIBRARIES/$(basename $RAWPATH)/ANALYSIS/ -type f -name "*.primertrimmed.rg.sorted.bam" | while read o; do basename $o | cut -d. -f1; done | sort | uniq); do fastcov -l $HOME/VirWGS/LIBRARIES/$(basename $RAWPATH)/ANALYSIS/"$i".primertrimmed.rg.sorted.bam -o $HOME/VirWGS/LIBRARIES/$(basename $RAWPATH)/ANALYSIS/"$i".coverage.pdf; done # https://github.com/RaverJay/fastcov
    gs -dSAFER -r3000 -sDEVICE=pdfwrite -dNOPAUSE -dBATCH -sOUTPUTFILE=$HOME/VirWGS/LIBRARIES/$(basename $RAWPATH)/CONSENSUS/$(basename $RAWPATH).depth.pdf $HOME/VirWGS/LIBRARIES/$(basename $RAWPATH)/ANALYSIS/*.pdf; done
fi

rm -rf $HOME/VirWGS/LIBRARIES/$(basename $RAWPATH)/ANALYSIS/*.reference.fasta*

rm -rf $HOME/VirWGS/LIBRARIES/$(basename $RAWPATH)/ANALYSIS/*.score.bed

tar -czf $HOME/VirWGS/LIBRARIES/$(basename $RAWPATH).tar.gz -P $HOME/VirWGS/LIBRARIES/$(basename $RAWPATH)*

[ -f ./nohup.out ] && rm -rf ./nohup.out
