#!/bin/bash

# CUDA on WSL2: https://developer.nvidia.com/cuda/wsl/download | https://hackmd.io/@Miles/rkYKDHPsO

USER=lpmor22

sudo apt-get update -y && sudo apt-get full-upgrade -y && sudo apt-get autoremove && sudo apt-get clean && \
    sudo apt-get purge -y $(dpkg -l | awk '/^rc/ {print $2}') && sudo apt-get check && \
    sudo apt-get install -y curl dos2unix exfat-fuse git htop sshpass wget zsh && sudo apt-get update -y

[ ! -d $HOME/bin ] && cd && mkdir $HOME/bin && mv $HOME/labstuffs/etc/* $HOME/labstuffs/phy/* $HOME/bin && \
    chmod 777 -R $HOME/bin

[ ! -f /mnt/c/Users/"$USER"/.wslconfig ] && mv $HOME/labstuffs/configs/.wslconfig /mnt/c/Users/"$USER"

if [[ -z "$(zsh --version)" ]]; then
    sudo chsh --shell /bin/zsh "$USER"
    sh -c $(wget https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh -O -)
    wsl.exe --shutdown
fi

if [[ ! -z "$(zsh --version)" ]]; then
    git clone https://github.com/zsh-users/zsh-syntax-highlighting.git \
        ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
    sh -c $(curl -fsSL https://git.io/zinit-install)
fi

if [[ -z "$(nvidia-smi)" ]]; then
    sudo apt-key adv --fetch-keys http://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/7fa2af80.pub
    sudo sh -c 'echo "deb http://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64 /" > /etc/apt/sources.list.d/cuda.list'
    sudo apt-get update && sudo apt-get install -y cuda-toolkit-11-0 nvidia-cuda-toolkit && \
        sudo apt-get install --fix-missing
    sudo sh -c 'echo "deb http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu2004/x86_64 /" > /etc/apt/sources.list.d/nvidia-machine-learning.list'
    wsl.exe --shutdown
fi
