#!/bin/bash

source activate vgap_assembly

artic_vcf_filter --medaka "$2".merged.vcf "$2".pass.vcf "$2".fail.vcf
bgzip -f "$2".pass.vcf
tabix -p vcf "$2".pass.vcf.gz
artic_make_depth_mask --store-rg-depths "$1" "$2".primertrimmed.rg.sorted.bam "$2".coverage_mask.txt
artic_mask "$1" "$2".coverage_mask.txt "$2".fail.vcf "$2".preconsensus.fasta
bcftools consensus -f "$2".preconsensus.fasta "$2".pass.vcf.gz -m "$2".coverage_mask.txt -o "$2".consensus.fasta
artic_fasta_header "$2".consensus.fasta ""$2"/ARTIC/medaka"
cat "$2".consensus.fasta "$1" > "$2".muscle.in.fasta
muscle -in "$2".muscle.in.fasta -out "$2".muscle.out.fasta

REVCOV=$(paste <(fastalength "$1" | awk '{print $1}') <(seqtk comp "$2".consensus.fasta | awk -F"\t" '{print $9}') | awk -F"\t" '{printf("%0.2f\n", ($1-$2)/$1*100)}')
NCOUNT=$(seqtk comp "$2".consensus.fasta | awk -F"\t" '{print $9}')
NCOUNTPER=$(paste <(seqtk comp "$2".consensus.fasta | awk -F"\t" '{print $9}') <(fastalength "$1" | awk '{print $1}') | awk -F"\t" '{printf("%0.2f\n", ($1/$2)*100)}')

echo ""
echo "$REVCOV""#""$NCOUNT""#""$NCOUNTPER" | tr '#' '\t'
