#!/bin/bash

MYSHELL="$(echo "$SHELL" | awk -F/ '{print $NF}')"

GUPPY_VERSION=v6.0.1 # Updated Jan 08 2022

if [[ -z "$(which guppy_basecaller)" ]]; then
    cd
    curl https://mirror.oxfordnanoportal.com/software/analysis/ont-guppy_"$GUPPY_VERSION"_linux64.tar.gz -o ont-guppy.tar.gz
    tar -vzxf ont-guppy.tar.gz
    rm -rf ont-guppy.tar.gz
    echo 'export PATH="$HOME"/ont-guppy/bin:/usr/local/share/rsi/idl/bin:"$PATH"' >> "$HOME"/."$(MYSHELL)"rc
    export PATH="$HOME"/ont-guppy/bin:/usr/local/share/rsi/idl/bin:"$PATH"
elif [[ "$(guppy_basecaller --version | awk -F" " '{print $NF}' | awk -F+ '{print $1}' | sed -n '1p')" < "$GUPPY_VERSION" ]]; then
    cd
    rm -rf ont-guppy
    curl https://mirror.oxfordnanoportal.com/software/analysis/ont-guppy_"$GUPPY_VERSION"_linux64.tar.gz -o ont-guppy.tar.gz
    tar -vzxf ont-guppy.tar.gz
    rm -rf ont-guppy.tar.gz
else
    guppy_basecaller --version
fi
