#!/bin/bash

[ ! -d "$HOME"/SARS2_HumanFiltered ] && mkdir "$HOME"/SARS2_HumanFiltered "$HOME"/SARS2_HumanFiltered/depth10 \
    "$HOME"/SARS2_HumanFiltered/depth10_HFilt

bg() {

    start=$(date +%s.%N)

    THREADS=$(lscpu | grep 'CPU(s):' | awk '{print $2}' | sed -n '1p' | awk '{print $1-2}')

    [ ! -f "$HOME"/SARS2_HumanFiltered/GRCh38.p13.genome.fa.gz ] && \
	wget http:/ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_38/GRCh38.p13.genome.fa.gz -q \
        -O "$HOME"/SARS2_HumanFiltered/GRCh38.p13.genome.fa.gz

    [ ! -f "$HOME"/SARS2_HumanFiltered/summary.tmp ] && echo "SampleId#NumberTotalReads#NumberTotalReadsFilt#NumberReadsMapped#NumberReadsMappedFilt#AverageDepth#AverageDepthFilt#Depth10x#Depth10xFilt#Depth100x#Depth100xFilt#Depth1000x#Depth1000xFilt#ReferenceCoverage#ReferenceCoverageFilt#NCount#NCountFilt#NCountPercent#NCountPercentFilt#PangolinVersion#PangoLearnVersion#PangoLineage#PangoLineageFilt#NextcladeVersion#Clade#CladeFilt#Substitutions#SubstitutionsFilt#Deletions#DeletionsFilt#Insertions#InsertionsFilt#Missing#MissingFilt#aaSubstitutions#aaSubstitutionsFilt#aaDeletions#aaDeletionsFilt" | \
        tr '#' '\t' > "$HOME"/SARS2_HumanFiltered/summary.tmp

    for i in $(find "$PWD" -type f -name "*.bam" | sort); do
        SAMPLEFILE=$(echo "$i" | awk -F/ '{print $NF"_"$(NF-2)}' | sed 's/_ANALYSIS//' | sed 's/.bam//')
        SAMPLEID=$(echo "$i" | awk -F'/' '{print $NF}' | awk -F. '{print $1}')
        source activate igm_sarscov2
        bwa index "$HOME"/SARS2_HumanFiltered/GRCh38.p13.genome.fa.gz
        bwa mem -t "$THREADS" "$HOME"/SARS2_HumanFiltered/GRCh38.p13.genome.fa.gz \
            "$PWD"/"$SAMPLEID".results/"$SAMPLEID".R1.fq.gz "$PWD"/"$SAMPLEID".results/"$SAMPLEID".R2.fq.gz | \
            samtools sort -@ "$THREADS" -o "$HOME"/SARS2_HumanFiltered/depth10_HFilt/"$SAMPLEFILE".GRCh38p13.bam -
        samtools index -@ "$THREADS" "$HOME"/SARS2_HumanFiltered/depth10_HFilt/"$SAMPLEFILE".GRCh38p13.bam
        samtools fastq -@ "$THREADS" -f 4 "$HOME"/SARS2_HumanFiltered/depth10_HFilt/"$SAMPLEFILE".GRCh38p13.bam \
            > "$HOME"/SARS2_HumanFiltered/depth10_HFilt/"$SAMPLEFILE".GRCh38p13.unmaped.fastq
        bwa index "$HOME"/IGM_SARSCOV2/MN908947.3.fasta
        bwa mem -t "$THREADS" "$HOME"/IGM_SARSCOV2/MN908947.3.fasta \
            "$HOME"/SARS2_HumanFiltered/depth10_HFilt/"$SAMPLEFILE".GRCh38p13.unmaped.fastq | samtools sort \
            -@ "$THREADS" -o "$HOME"/SARS2_HumanFiltered/depth10_HFilt/"$SAMPLEFILE".SARS2.sorted.bam -
        samtools mpileup -d 50000 --reference "$HOME"/IGM_SARSCOV2/MN908947.3.fasta -a \
            -B "$HOME"/SARS2_HumanFiltered/depth10_HFilt/"$SAMPLEFILE".SARS2.sorted.bam | \
            ivar variants -p "$HOME"/SARS2_HumanFiltered/depth10_HFilt/"$SAMPLEFILE" -q 30 -t 0.05
        samtools mpileup -d 50000 --reference "$HOME"/IGM_SARSCOV2/MN908947.3.fasta -a \
            -B "$HOME"/SARS2_HumanFiltered/depth10_HFilt/"$SAMPLEFILE".SARS2.sorted.bam | \
            ivar consensus -p "$HOME"/SARS2_HumanFiltered/depth10_HFilt/"$SAMPLEFILE" -q 30 -t 0 -m 10 -n N
        samtools mpileup -d 50000 --reference "$HOME"/IGM_SARSCOV2/MN908947.3.fasta -a \
            -B "$HOME"/SARS2_HumanFiltered/depth10_HFilt/"$SAMPLEFILE".SARS2.sorted.bam | \
            ivar consensus -p "$HOME"/SARS2_HumanFiltered/depth10_HFilt/"$SAMPLEFILE".ivar060 -q 30 -t 0.60 -m 10 -n N
        echo -n "#" | tr '#' '\n' >> "$HOME"/SARS2_HumanFiltered/summary.tmp
        echo -n "$SAMPLEID""#" | tr '#' '\t' >> "$HOME"/SARS2_HumanFiltered/summary.tmp
        samtools view -c "$PWD"/"$SAMPLEID".results/"$SAMPLEID".sorted.bam | awk '{printf $0"#"}' | \
            tr '#' '\t' >> "$HOME"/SARS2_HumanFiltered/summary.tmp
        samtools view -c "$HOME"/SARS2_HumanFiltered/depth10_HFilt/"$SAMPLEFILE".SARS2.sorted.bam | \
            awk '{printf $0"#"}' | tr '#' '\t' >> "$HOME"/SARS2_HumanFiltered/summary.tmp
        samtools view -c -h -F 4 "$PWD"/"$SAMPLEID".results/"$SAMPLEID".sorted.bam | awk '{printf $0"#"}' | \
            tr '#' '\t' >> "$HOME"/SARS2_HumanFiltered/summary.tmp
        samtools view -c -h -F 4 "$HOME"/SARS2_HumanFiltered/depth10_HFilt/"$SAMPLEFILE".SARS2.sorted.bam | \
            awk '{printf $0"#"}' | tr '#' '\t' >> "$HOME"/SARS2_HumanFiltered/summary.tmp
        AVGDEPTH=$(samtools depth "$PWD"/"$SAMPLEID".results/"$SAMPLEID".sorted.bam | \
            awk '{sum+=$3} END {print sum/NR}')
        AVGDEPTH_HFILT=$(samtools depth "$HOME"/SARS2_HumanFiltered/depth10_HFilt/"$SAMPLEFILE".SARS2.sorted.bam | \
            awk '{sum+=$3} END {print sum/NR}')
        if [[ "$AVGDEPTH" == 0 ]]; then
            echo "0""#" | tr '#' '\t' | tr -d '\n' >> "$HOME"/SARS2_HumanFiltered/summary.tmp
        else
            echo "$AVGDEPTH" | awk '{printf $0"#"}' | tr '#' '\t' | \
                tr -d '\n' >> "$HOME"/SARS2_HumanFiltered/summary.tmp
        fi
        if [[ "$AVGDEPTH_HFIL" == 0 ]]; then
            echo "0""#" | tr '#' '\t' | tr -d '\n' >> "$HOME"/SARS2_HumanFiltered/summary.tmp
        else
            echo "$AVGDEPTH_HFILT" | awk '{printf $0"#"}' | tr '#' '\t' | \
                tr -d '\n' >> "$HOME"/SARS2_HumanFiltered/summary.tmp
        fi
        paste <(samtools depth "$PWD"/"$SAMPLEID".results/"$SAMPLEID".sorted.bam | \
            awk '{if ($3 > '"10"') {print $0}}' | wc -l) <(fastalength "$HOME"/IGM_SARSCOV2/MN908947.3.fasta | \
            awk '{print $1}') | awk -F"\t" '{printf("%0.2f\n", $1/$2*100)}' | awk '{printf $0"#"}' | \
            tr '#' '\t' >> "$HOME"/SARS2_HumanFiltered/summary.tmp
        paste <(samtools depth "$HOME"/SARS2_HumanFiltered/depth10_HFilt/"$SAMPLEFILE".SARS2.sorted.bam | \
            awk '{if ($3 > '"10"') {print $0}}' | wc -l) <(fastalength "$HOME"/IGM_SARSCOV2/MN908947.3.fasta | \
            awk '{print $1}') | awk -F"\t" '{printf("%0.2f\n", $1/$2*100)}' | awk '{printf $0"#"}' | \
            tr '#' '\t' >> "$HOME"/SARS2_HumanFiltered/summary.tmp
        paste <(samtools depth "$PWD"/"$SAMPLEID".results/"$SAMPLEID".sorted.bam | \
            awk '{if ($3 > '"100"') {print $0}}' | wc -l) <(fastalength "$HOME"/IGM_SARSCOV2/MN908947.3.fasta | \
            awk '{print $1}') | awk -F"\t" '{printf("%0.2f\n", $1/$2*100)}' | awk '{printf $0"#"}' | \
            tr '#' '\t' >> "$HOME"/SARS2_HumanFiltered/summary.tmp
        paste <(samtools depth "$HOME"/SARS2_HumanFiltered/depth10_HFilt/"$SAMPLEFILE".SARS2.sorted.bam | \
            awk '{if ($3 > '"100"') {print $0}}' | wc -l) <(fastalength "$HOME"/IGM_SARSCOV2/MN908947.3.fasta | \
            awk '{print $1}') | awk -F"\t" '{printf("%0.2f\n", $1/$2*100)}' | awk '{printf $0"#"}' | \
            tr '#' '\t' >> "$HOME"/SARS2_HumanFiltered/summary.tmp
        paste <(samtools depth "$PWD"/"$SAMPLEID".results/"$SAMPLEID".sorted.bam | \
            awk '{if ($3 > '"1000"') {print $0}}' | wc -l) <(fastalength "$HOME"/IGM_SARSCOV2/MN908947.3.fasta | \
            awk '{print $1}') | awk -F"\t" '{printf("%0.2f\n", $1/$2*100)}' | awk '{printf $0"#"}' | \
            tr '#' '\t' >> "$HOME"/SARS2_HumanFiltered/summary.tmp
        paste <(samtools depth "$HOME"/SARS2_HumanFiltered/depth10_HFilt/"$SAMPLEFILE".SARS2.sorted.bam | \
            awk '{if ($3 > '"1000"') {print $0}}' | wc -l) <(fastalength "$HOME"/IGM_SARSCOV2/MN908947.3.fasta | \
            awk '{print $1}') | awk -F"\t" '{printf("%0.2f\n", $1/$2*100)}' | awk '{printf $0"#"}' | \
            tr '#' '\t' >> "$HOME"/SARS2_HumanFiltered/summary.tmp
        NCOUNT=$(seqtk comp "$PWD"/"$SAMPLEID".results/"$SAMPLEID".depth10.fa | awk -F"\t" '{print $9}')
        NCOUNT_HFILT=$(seqtk comp "$HOME"/SARS2_HumanFiltered/depth10_HFilt/"$SAMPLEFILE".fa | \
            awk -F"\t" '{print $9}')
        REVCOV=$(paste <(fastalength "$HOME"/IGM_SARSCOV2/MN908947.3.fasta | awk '{print $1}') \
            <(seqtk comp "$PWD"/"$SAMPLEID".results/"$SAMPLEID".depth10.fa | awk -F"\t" '{print $9}') | \
            awk -F"\t" '{printf("%0.2f\n", ($1-$2)/$1*100)}')
        REVCOV_HFILT=$(paste <(fastalength "$HOME"/IGM_SARSCOV2/MN908947.3.fasta | awk '{print $1}') \
            <(seqtk comp "$HOME"/SARS2_HumanFiltered/depth10_HFilt/"$SAMPLEFILE".fa | \
            awk -F"\t" '{print $9}') | awk -F"\t" '{printf("%0.2f\n", ($1-$2)/$1*100)}')
        NCOUNTPER=$(paste <(seqtk comp "$PWD"/"$SAMPLEID".results/"$SAMPLEID".depth10.fa | \
            awk -F"\t" '{print $9}') <(fastalength "$HOME"/IGM_SARSCOV2/MN908947.3.fasta | awk '{print $1}') | \
            awk -F"\t" '{printf("%0.2f\n", ($1/$2)*100)}')
        NCOUNTPER_HFILT=$(paste <(seqtk comp "$HOME"/SARS2_HumanFiltered/depth10_HFilt/"$SAMPLEFILE".fa | \
            awk -F"\t" '{print $9}') <(fastalength "$HOME"/IGM_SARSCOV2/MN908947.3.fasta | awk '{print $1}') | \
            awk -F"\t" '{printf("%0.2f\n", ($1/$2)*100)}')
        if [[ "$NCOUNT" == 0 ]]; then
            echo "0""#" | tr '#' '\t' | tr -d '\n' >> "$HOME"/SARS2_HumanFiltered/summary.tmp
        else
            echo "$REVCOV" | awk '{printf $0"#"}' | tr '#' '\t' | \
                tr -d '\n' >> "$HOME"/SARS2_HumanFiltered/summary.tmp
        fi
        if [[ "$NCOUNT_HFILT" == 0 ]]; then
            echo "0""#" | tr '#' '\t' | tr -d '\n' >> "$HOME"/SARS2_HumanFiltered/summary.tmp
        else
            echo "$REVCOV_HFILT" | awk '{printf $0"#"}' | tr '#' '\t' | \
                tr -d '\n' >> "$HOME"/SARS2_HumanFiltered/summary.tmp
        fi
        if [[ "$NCOUNT" == 0 ]]; then
            echo "29903""#" | tr '#' '\t' | tr -d '\n' >> "$HOME"/SARS2_HumanFiltered/summary.tmp
        else
            echo "$NCOUNT" | awk '{printf $0"#"}' | tr '#' '\t' | \
                tr -d '\n' >> "$HOME"/SARS2_HumanFiltered/summary.tmp
        fi
        if [[ "$NCOUNT_HFILT" == 0 ]]; then
            echo "29903""#" | tr '#' '\t' | tr -d '\n' >> "$HOME"/SARS2_HumanFiltered/summary.tmp
        else
            echo "$NCOUNT_HFILT" | awk '{printf $0"#"}' | tr '#' '\t' | \
                tr -d '\n' >> "$HOME"/SARS2_HumanFiltered/summary.tmp
        fi
        if [[ "$NCOUNT" == 0 ]]; then
            echo "100""#" | tr '#' '\t' | tr -d '\n' >> "$HOME"/SARS2_HumanFiltered/summary.tmp
        else
            echo "$NCOUNTPER" | awk '{printf $0"#"}' | tr '#' '\t' | \
                tr -d '\n' >> "$HOME"/SARS2_HumanFiltered/summary.tmp
        fi
        if [[ "$NCOUNT_HFILT" == 0 ]]; then
            echo "100""#" | tr '#' '\t' | tr -d '\n' >> "$HOME"/SARS2_HumanFiltered/summary.tmp
        else
            echo "$NCOUNTPER_HFILT" | awk '{printf $0"#"}' | tr '#' '\t' | \
                tr -d '\n' >> "$HOME"/SARS2_HumanFiltered/summary.tmp
        fi
        cat "$PWD"/"$SAMPLEID".results/"$SAMPLEID".depth10.fa >> "$HOME"/SARS2_HumanFiltered/preconsensus.tmp
        cat "$HOME"/SARS2_HumanFiltered/depth10_HFilt/"$SAMPLEFILE".fa >> \
            "$HOME"/SARS2_HumanFiltered/preconsensus_hfilt.tmp
        source activate pangolin
        pangolin "$PWD"/"$SAMPLEID".results/"$SAMPLEID".depth10.fa -t "$THREADS" \
            --outfile "$HOME"/SARS2_HumanFiltered/depth10/"$SAMPLEFILE".lineage_report.csv
        pangolin "$HOME"/SARS2_HumanFiltered/depth10_HFilt/"$SAMPLEFILE".fa -t "$THREADS" \
            --outfile "$HOME"/SARS2_HumanFiltered/depth10_HFilt/"$SAMPLEFILE".lineage_report.csv
        cat "$HOME"/SARS2_HumanFiltered/depth10/"$SAMPLEFILE".lineage_report.csv | sed -n 2p | \
            awk -F, '{print $9"\t"$10"\t"$2}' | awk '{printf $0"#"}' | \
            tr '#' '\t' >> "$HOME"/SARS2_HumanFiltered/summary.tmp
        cat "$HOME"/SARS2_HumanFiltered/depth10_HFilt/"$SAMPLEFILE".lineage_report.csv | sed -n 2p | \
            awk -F, '{print $2}' | awk '{printf $0"#"}' | \
            tr '#' '\t' >> "$HOME"/SARS2_HumanFiltered/summary.tmp
        source activate nextclade
        nextclade --version | awk '{printf $0"#"}' | tr '#' '\t' >> "$HOME"/SARS2_HumanFiltered/summary.tmp
        nextclade -i "$PWD"/"$SAMPLEID".results/"$SAMPLEID".depth10.fa -j "$THREADS" \
            -c "$HOME"/SARS2_HumanFiltered/depth10/"$SAMPLEFILE".nextclade.csv
        nextclade -i "$HOME"/SARS2_HumanFiltered/depth10_HFilt/"$SAMPLEFILE".fa -j "$THREADS" \
            -c "$HOME"/SARS2_HumanFiltered/depth10_HFilt/"$SAMPLEFILE".nextclade.csv
        cat "$HOME"/SARS2_HumanFiltered/depth10/"$SAMPLEFILE".nextclade.csv | sed -n 2p | tr ";" "\t" | \
            awk -F"\t" '{print $2}' | awk '{printf $0"#"}' | tr '#' '\t' >> "$HOME"/SARS2_HumanFiltered/summary.tmp
        cat  "$HOME"/SARS2_HumanFiltered/depth10_HFilt/"$SAMPLEFILE".nextclade.csv | sed -n 2p | tr ";" "\t" | \
            awk -F"\t" '{print $2}' | awk '{printf $0"#"}' | tr '#' '\t' >> "$HOME"/SARS2_HumanFiltered/summary.tmp
        cat "$HOME"/SARS2_HumanFiltered/depth10/"$SAMPLEFILE".nextclade.csv | sed -n 2p | tr ";" "\t" | \
            awk -F"\t" '{print $11}' | awk '{printf $0"#"}' | tr '#' '\t' >> "$HOME"/SARS2_HumanFiltered/summary.tmp
        cat  "$HOME"/SARS2_HumanFiltered/depth10_HFilt/"$SAMPLEFILE".nextclade.csv | sed -n 2p | tr ";" "\t" | \
            awk -F"\t" '{print $11}' | awk '{printf $0"#"}' | tr '#' '\t' >> "$HOME"/SARS2_HumanFiltered/summary.tmp
        cat "$HOME"/SARS2_HumanFiltered/depth10/"$SAMPLEFILE".nextclade.csv | sed -n 2p | tr ";" "\t" | \
            awk -F"\t" '{print $12}' | awk '{printf $0"#"}' | tr '#' '\t' >> "$HOME"/SARS2_HumanFiltered/summary.tmp
        cat  "$HOME"/SARS2_HumanFiltered/depth10_HFilt/"$SAMPLEFILE".nextclade.csv | sed -n 2p | tr ";" "\t" | \
            awk -F"\t" '{print $12}' | awk '{printf $0"#"}' | tr '#' '\t' >> "$HOME"/SARS2_HumanFiltered/summary.tmp
        cat "$HOME"/SARS2_HumanFiltered/depth10/"$SAMPLEFILE".nextclade.csv | sed -n 2p | tr ";" "\t" | \
            awk -F"\t" '{print $13}' | awk '{printf $0"#"}' | tr '#' '\t' >> "$HOME"/SARS2_HumanFiltered/summary.tmp
        cat  "$HOME"/SARS2_HumanFiltered/depth10_HFilt/"$SAMPLEFILE".nextclade.csv | sed -n 2p | tr ";" "\t" | \
            awk -F"\t" '{print $13}' | awk '{printf $0"#"}' | tr '#' '\t' >> "$HOME"/SARS2_HumanFiltered/summary.tmp
        cat "$HOME"/SARS2_HumanFiltered/depth10/"$SAMPLEFILE".nextclade.csv | sed -n 2p | tr ";" "\t" | \
            awk -F"\t" '{print $14}' | awk '{printf $0"#"}' | tr '#' '\t' >> "$HOME"/SARS2_HumanFiltered/summary.tmp
        cat  "$HOME"/SARS2_HumanFiltered/depth10_HFilt/"$SAMPLEFILE".nextclade.csv | sed -n 2p | tr ";" "\t" | \
            awk -F"\t" '{print $14}' | awk '{printf $0"#"}' | tr '#' '\t' >> "$HOME"/SARS2_HumanFiltered/summary.tmp
        cat "$HOME"/SARS2_HumanFiltered/depth10/"$SAMPLEFILE".nextclade.csv | sed -n 2p | tr ";" "\t" | \
            awk -F"\t" '{print $17}' | awk '{printf $0"#"}' | tr '#' '\t' >> "$HOME"/SARS2_HumanFiltered/summary.tmp
        cat  "$HOME"/SARS2_HumanFiltered/depth10_HFilt/"$SAMPLEFILE".nextclade.csv | sed -n 2p | tr ";" "\t" | \
            awk -F"\t" '{print $17}' | awk '{printf $0"#"}' | tr '#' '\t' >> "$HOME"/SARS2_HumanFiltered/summary.tmp
        cat "$HOME"/SARS2_HumanFiltered/depth10/"$SAMPLEFILE".nextclade.csv | sed -n 2p | tr ";" "\t" | \
            awk -F"\t" '{print $19}' | awk '{printf $0"#"}' | tr '#' '\t' >> "$HOME"/SARS2_HumanFiltered/summary.tmp
        cat  "$HOME"/SARS2_HumanFiltered/depth10_HFilt/"$SAMPLEFILE".nextclade.csv | sed -n 2p | tr ";" "\t" | \
            awk -F"\t" '{print $19}' | awk '{printf $0}' >> "$HOME"/SARS2_HumanFiltered/summary.tmp
    done

    sed '/^[[:space:]]*$/d' "$HOME"/SARS2_HumanFiltered/summary.tmp > \
        "$HOME"/SARS2_HumanFiltered/SARS2_HumanFiltered_summary_$(uname -n)_$(date +'%Y-%m-%d').txt

    source activate igm_sarscov2

    mafft --thread "$THREADS" --quiet --auto --keeplength --inputorder --6merpair --leavegappyregion \
        --addfragments "$HOME"/SARS2_HumanFiltered/preconsensus.tmp "$HOME"/IGM_SARSCOV2/MN908947.3.fasta | \
        seqkit grep -vip MN908947.3 | sed '/>/!y/atcgn-/ATCGNN/' >> \
        "$HOME"/SARS2_HumanFiltered/SARS2_consensus_$(uname -n)_$(date +'%Y-%m-%d').fasta

    mafft --thread "$THREADS" --quiet --auto --keeplength --inputorder --6merpair --leavegappyregion \
        --addfragments "$HOME"/SARS2_HumanFiltered/preconsensus_hfilt.tmp "$HOME"/IGM_SARSCOV2/MN908947.3.fasta | \
        seqkit grep -vip MN908947.3 | sed '/>/!y/atcgn-/ATCGNN/' >> \
        "$HOME"/SARS2_HumanFiltered/SARS2_consensus_hfilt_$(uname -n)_$(date +'%Y-%m-%d').fasta

    rm -rf "$HOME"/IGM_SARSCOV2/MN908947.3.fasta.* "$HOME"/SARS2_HumanFiltered/*.tmp

    end=$(date +%s.%N)

    runtime=$(python -c "print(${end} - ${start})")

    echo "" && echo "Done. The runtime was "$runtime" seconds." && echo ""

}

bg &>>"$HOME"/SARS2_HumanFiltered/SARS2_HumanFiltered_log_$(uname -n)_$(date +'%Y-%m-%d').txt &
